apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: my-nginx1
  labels:
    name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      name: nginx1
  template:
    metadata:
      namespace: my-nginx1
      labels:
        name: nginx1
    spec:
      containers:
      - name: nginx1
        image: nginx
        ports:
        - containerPort: 81

